### ISSUE TITLE
额 新手对推荐系统感兴趣 怎么学习你这个项目呢

### ISSUE THREAD

**Issue by murdonson** [jasonTangxd/recommendSys#1]
hadoop kafa什么的我都没接触过 学习顺序是什么呢(⊙o⊙)…?

**Comment by jasonTangxd** [comment]
可以看看我之前写的一些博客，blog.xiaoxiaomo.com 
如果都没接触过，想学习hadoop kafka这些就可以从hadoop先学习走
如果只是想学习推荐系统，只是对算法部分感兴趣，可以看看协同过滤等推荐算法，慢慢向外扩散
